### ISSUE TITLE
altas downgrade to Gkui

### ISSUE THREAD

**Issue by mreros** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#1]
got GKUI firmware ? need downgrade to gkui

**Comment by xeon1989** [comment]
what's your hardware version?

**Comment by ghubbunny** [comment]
second that request, sir. i'm on hardware 0090

**Comment by xeon1989** [comment]
@mreros @ghubbunny only work with Premium/FS IHU with hardware version 0090. DO NOT flash this firmware to IHU with hardware version 0200 or any other versions.
As usual, proceed with caution. :) 
https://drive.google.com/file/d/13GULa8ZK8PuBFL70JdKWl2siP7LpY57D/view?usp=share_link

**Comment by ghubbunny** [comment]
Many thanks, Xeon. Truly appreciated.
BTW, no need for hash, right? As long as "unzip -t " on the file shows "No errors..."?

**Comment by xeon1989** [comment]
@ghubbunny this is the hash, it's always good to ensure integrity and authenticity of the file. 

![image](https://user-images.githubusercontent.com/17538895/234158345-8f2f6d4a-d91a-4f71-b2f7-1abf88d66a07.png)

**Comment by ghubbunny** [comment]
Thanks
