### ISSUE TITLE
No longer receive updates after downgrade to ATLAS version 617v1 / 618v1

### ISSUE THREAD

**Issue by Ninetai1z** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#10]
Hello xeon1989. I have downgraded my ATLAS version from 644 to 617v1/618v1. Then, after I've installed the Proton X50 APK, i've found that some apps not functioning properly such as newpipe. So i decided to uninstall the apk by using the uninstallation script given by you. So now my ATLAS is like the stock one version 617v1/618v1 but i haven't received a new update for about 2 months. Is there any way to fix this?

**Comment by xeon1989** [comment]
Hi, SC should able to perform manual upgrade to version 644.
I did not keep the 644 firmware handy, if you know someone having 644 firmware (i saw know someone shared before back in June) you may upgrade it yourself with the same method as the downgrade.
