### ISSUE TITLE
Autofold mirror does not function after downgrading

### ISSUE THREAD

**Issue by Loon23** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#11]
It seems like the autofold mirror after locking the car doesn't work. Any solution?

**Comment by xeon1989** [comment]
have you tried this?
https://m.youtube.com/watch?v=kHYOAdc4nq8
12:41
![Uploading Screenshot_2023-10-15-19-35-01-217_com.android.chrome-edit.jpg…]()

**Comment by Loon23** [comment]
Yes, the function is already turned on

**Comment by Loon23** [comment]
Problem Solved.

**Comment by Loon23** [comment]
Problem Solved
