### ISSUE TITLE
Sideload not installed 

### ISSUE THREAD

**Issue by revolutionaries9** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#12]
Hi. I manage to flash my firmware to 617 but apparently the sideload apps are not installed. I thought the problem was I downloaded the script form macos and attempt again to download is using windows but unfortunately the sideload apps are still not install. Can kindly help?

**Comment by xeon1989** [comment]
can you please show the content of your USB under Windows?

**Comment by revolutionaries9** [comment]
Hi. This is my USB content. Attempted to uninstall and reinstall back this morning but the only additional apps. was install is QD Link App. I also attached the output text.
<img width="922" alt="Screenshot 2023-10-28 at 10 53 30 AM" src="https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/126466430/903944e1-ec71-479e-85bf-721bcb39e653">
<img width="926" alt="Screenshot 2023-10-28 at 10 48 53 AM" src="https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/126466430/de6a076f-b1ac-444b-ab16-d8d285ab3ddf">
[outputInstall_1698397828.txt](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/files/13194260/outputInstall_1698397828.txt)

[outputUninstall_1698457736.txt](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/files/13194261/outputUninstall_1698457736.txt)

**Comment by xeon1989** [comment]
Hi, thanks for providing the logs.
I analyzed the outputInstall and noticed that some files generated in MacOS got copied over,
It can be seen in line 308 onwards.

> ========show app directory after copy=======
> -rwxr-xr-x root     root         4096 2023-10-26 21:40 _**._cn.manstep.phonemirrorBox.apk**_
> -rwxr-xr-x root     root         4096 2023-10-26 21:40 _**._lib**_
> -rwxr-xr-x root     root      8659141 2023-10-27 17:10 cn.manstep.phonemirrorBox.apk
> drwxr-xr-x root     root              2023-10-26 21:16 lib


Since you Uninstalled, at least the app folder in IHU is clean. :) 
Please proceed to format the USB in Windows, then download and extract the app installer.
Afterwards you can plug it in IHU and try again.
