### ISSUE TITLE
Usb option disable in SOC mode

### ISSUE THREAD

**Issue by syauqishamsuri** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#13]
Dear Xeon,

thank you for the solution you shared with us. May all your good deeds will be bless. 

I have one issue when i tried to flash my IhU. I successfully follow all those step and got blocker when i enter the SOC mode. 
![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/25292367/299cde08-5b47-4f41-b115-749119741108)
Somehow the USB option is disabled (grey out). I have tried two different usb but the issue still persist (both format to FAT ady)

do you know how i can overcome this issue. Thank you Xeon. 

Best Regards,
SS

**Comment by xeon1989** [comment]
Once download you need to extract only once and paste the .zip file into the USB drive.
Would you mind the share the content of your USB drive?

**Comment by syauqishamsuri** [comment]
Sure xeon. 

As attached. 
![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/25292367/3206724f-ef4f-45e2-9b2e-60a481ee4556)

![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/25292367/92d99c57-d323-49d8-beaf-a1fba4daab5f)

This is the usb drive info

![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/25292367/fd35cf29-a459-4ff9-b105-b8ea8c47de9a)

**Comment by xeon1989** [comment]
This is incorrect.
Once downloaded "Proton X50 Premium Flagship.7z" or "Proton X50 Standard Executive.7z", you should unzip the file and get either "SW0SXRA1124H5170.00617_1669692523000.zip" or "SW0SXRA1124L5170.00618_1675328454000.zip".
Then, copy that .zip file into USB drive.  

Content of your USB drive should looks similar to this.
![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/17538895/8779a753-681f-422e-aabf-9c305be53e12)

**Comment by syauqishamsuri** [comment]
i dont get the same zipfile name as yours.
mine is as per below: 
SW0SXRA1124H5170.00617.zip
![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/25292367/a0cdf6bf-183d-4e33-8c6b-46df13543a84)


is this correct?

**Comment by xeon1989** [comment]
Yes, this is fine.
