### ISSUE TITLE
Flashing the firmware while on v617 v1

### ISSUE THREAD

**Issue by ZhengYang94** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#14]
Hi Xeon, firstly thanks for providing the script.

My question would be,

1. I am currently on V617 V1, can i flash the firmware again so that i could get a fresh start? (the reason for this is because there are some apps installed using other methods(Not your script) that i could not remove even with restoring factory settings, wondering if flashing this again would clear everything and start fresh.)

**Comment by xeon1989** [comment]
Hi, since it's same version, I couldn't be sure if it will clean up files.
Nevertheless, it worth a try since the effort is not huge IMO.

**Comment by ZhengYang94** [comment]
Thanks Xeon, Just flashed the firmware. It did clean off all custom installed apps but retains user settings and your optimization script.
