### ISSUE TITLE
Will it work if i copy the unzipped contents from Mac OS into USB drive?

### ISSUE THREAD

**Issue by donutlord99** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#15]
Hi,
just want to seek clarification on the below:

1. Can I use MacOS to unzip the downloaded file and put it into the pendrive? Reason i'm asking is because I read some users faced issues with installation of apk software into the headunit from Mac OS, hence additional steps were needed. Wondering if it additional steps would be needed for this downgrade exercise?

2. Is the end file in .zip format? SW0SXRA0413H5170.00644.zip ? Do i just have to copy this file into the pendrive (in .zip format)?

Thanks

**Comment by xeon1989** [comment]
1. No. Either copy again in Windows or delete .* files after copy on MacOS.
2. Yes and yes.
