### ISSUE TITLE
Upgrading from GKUI to Atlas

### ISSUE THREAD

**Issue by Amri1210** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#16]
Hi. I want to upgrade to Atlas. But i want to uninstall first. Already follow the steps and all, but when i plug the usb in IHU port, nothing happen. 

1. F or the uninstalling, i need to remove even the ES Explorer or just the side load apps (spotify, waze etc)? 

2. Can i proceed to upgrade with my current software version as picture? 

![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/154773303/1213b979-bff1-49b9-8535-bdbdae2d3b38)

**Comment by Amri1210** [comment]
And for the uninstalling, i need to remove even the ES Explorer or just the side load apps (spotify, waze etc)?

**Comment by xeon1989** [comment]
Hi @Amri1210, you own the rare gem - HW version 200 but came with GKUI. 
Are you sure you want to upgrade? 😃

You do not need to uninstall sideloaded app, once upgraded those app will be wiped off, including ES File Explorer. 

Yes, HW version 200 are supported. 
However, I have no way for you to rollback to GKUI in case you regretted after upgrade, so think twice before you proceed.

**Comment by Amri1210** [comment]
Oh i see. The main reason i want to upgrade is that i cannot log in to the proton account in IHU. Asked SC and they said need to upgrade to atlas because GKUI not supported to login anymore.

**Comment by xeon1989** [comment]
Proton stopped legacy cloud server in early of this year, which means all cloud based functionalities such as Proton maps activation no longer works.
I didnt expect Member area no longer works too. 

In your case, you could either update yourself with the guide in this repository, or send to SC so they update for you.
Take note that SC always update to latest version where sideloading app is not possible.
