### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by ilham9393** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#17]
Hi xeon i have an issue with my autofold side mirror and SC detect the ihu already sideload and they want to  reject my warranty,sc inform to restore back my os to the latest because they unable to update via pendrive,did you have any idea how can i revert back to the latest version.want to upgrade from 617 to 644

**Comment by xeon1989** [comment]
Hi, I am skeptical about their statement that they not able to update via USB drive as the manual update mechanism never changes as far as I know.

Nevertheless, could you please try followings script and see if it helps?
Once executed the script and reboot, try to perform OTA in Settings app.

If there is no new version showed in Settings app, reply again with the log file. 

[Remove USB Download Cache.zip](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/files/13928592/Remove.USB.Download.Cache.zip)

**Comment by ilham9393** [comment]
Hi xeon thanks for the reply i appreciate it,below are the report they said the issue are come from the ihu because i do 3rd party sideload.and many thanks for the file i will try the zip file and update you later.and for the log file where i can get the file.😊
![841cfa3b-88ba-448a-8d06-fb759b0e959e](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/156443697/e0daf1f8-8456-4f5d-a2af-f7bad4b80e67)
Update: after i try with the zip there is no update showing at ota.

**Comment by xeon1989** [comment]
Ho, could you attach the log please?
