### ISSUE TITLE
Upgrade GKUI to Atlas Together With Apps Installation Script

### ISSUE THREAD

**Issue by vibrain-g** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#18]
Hi Chris, can you help me to check if I doing the right thing paste the file in usb drive? herewith I attached picture for your references.

![FLASH TO ATLAS](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/124857794/87177bcf-b112-44e6-82be-8b15e2b4bc06)

**Comment by xeon1989** [comment]
No this is incorrect. You do not need to extract the firmware file (SW0SXRA..).

**Comment by vibrain-g** [comment]
Thank you bro for your fast respond, so, I'm just extract the file Proton X50 Standard Executive? below screenshot of changes I made. is that correct?

![latest](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/124857794/7a8a458c-ac3e-4ebf-a7b0-9f6fac69765a)

**Comment by xeon1989** [comment]
This should works

**Comment by vibrain-g** [comment]
Your help was like a superhero swooping in to save the day. Thank you a gazillion times over!
