### ISSUE TITLE
Unable to detect USB upgrade

### ISSUE THREAD

**Issue by Priest9969** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#19]
Hi, I'm accidentally upgrade to Atlas OS 644, and tried to downgrade back to 617.  Unfortunately, it seems like the upgrade file was not detected.  Below is some photo taken as info.
![20240305_210803 1](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/162336012/3c9e7897-567a-4a8f-bd23-ab19b73d6468)

Is the workable for downgrade OS 644 back to 617?

Thank you

**Comment by xeon1989** [comment]
Hi, I am not sure about the downgrade from 644 back to 617, but I do receive the feedback that it works the same as other version. 
Could you show me the content of your USB drive please?

**Comment by Priest9969** [comment]
Hi, Xeon. I'd found and understand the mistake made on the rightful file needed to copy to USB from your others chat.

Everythings is working fine after I copy the SWxxx617.zip to USB. Cause before this I copy the unzip folders and files.

I'd downgrade back in very 617 from 644.

Thank you.
