### ISSUE TITLE
issue trying to downgrade

### ISSUE THREAD

**Issue by chipochipo73** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#2]
i m getting stucked after the SOC chinese part...i can press on it but the following step which supposedly to be USB can't be clicked...any idea?

**Comment by xeon1989** [comment]
it seems to be issue with usb or files.
Can share content of your usb?

**Comment by fittodinno** [comment]
yeah me too.
![Uploading image.jpg…]()

**Comment by chipochipo73** [comment]
Cannot see Yr uploaded image fitto

**Comment by chipochipo73** [comment]
Let me snap a pic of the thumb drive

Macam cannot upload pics.. 😓

I also noticed the checksum like macam not the same.. 🤔

**Comment by fittodinno** [comment]
![Uploading IMG_8062.jpeg…]()


currently i extract file inside usb. before this just download the file & extract in usb. itu je. I try first

**Comment by chipochipo73** [comment]
I downloaded it onto pc... Then format USB fat 32...lepas tu extract all to the USB...but during the checksum I noticed got difference..but I proceeded to try... Can log into the system setting but until the part click USB... The button is not clickable...

**Comment by fittodinno** [comment]
how many time u extract zip file?

**Comment by chipochipo73** [comment]
Download time it's zip file... Then unzipped and copy all over... Macam sekali kot

**Comment by fittodinno** [comment]
now im trying extract another zip file after extract into usb. later i update if successful

**Comment by fittodinno** [comment]
bro i made it hahaha

**Comment by chipochipo73** [comment]
Omg... Then I silap mana... 😭

But how come u got so many unzipped times

**Comment by fittodinno** [comment]
0109811417 ws me bro we try sort out how

**Comment by xeon1989** [comment]
@chipochipo73 long story short, once you download, unzip once and place all files in USB drive.
The file "SW0SXRA1124H5170.00617.zip" or "SW0SXRA1124L5170.00618.zip" should be available in the root directory of your USB drive, then insert it.
You should see the button now available.

**Comment by chipochipo73** [comment]
Hi Xeon...thank you for the feedback...i finally managed to get it done after close to 10 various tries...hahaha,,,,but it works nonetheless....only issue now is the android auto...it keeps popping up the turn by turn navigation tab on the top right corner of the screen with a clicking sound...super annoying....any idea how to turn this pop up off?

**Comment by xeon1989** [comment]
Hi @chipochipo73 , sorry to hear that it take many attempt for you to get it done.
Would you mind to share which part of the guide could have improved to make it clearer? 

For Android Auto pop up, you may disable the Notification in Android native Settings.
Just go to "Open Hidden App" and block Android Auto showing notification. 

See this guide under "General" for details.
https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/blob/main/RecommendedSettings.md

**Comment by chipochipo73** [comment]
Morning Xeon.. I think Yr guide is clear but I m not quite sure which part actually gotten the USB button to work... I did all the formatting, unzipped and trial and error.. Haha

I m now trying to install the optimisation one... And still stuck at the wireless screen after 5 minutes... Nothing happening.. Haha

**Comment by xeon1989** [comment]
@chipochipo73  This is strange, if you see "Wireless Charging" screen, it indicates the start of script.
It should take less than 1 min. 
Once completed, it should show Android Settings app.
It will NOT restart itself since it's not needed. 

Could you reboot IHU by holding Power button, then try again?
Make sure the folder name "b832bc61472727635baffcf25dd28e9f239273e2" correct (the script will rename folder name once completed). 

You may also share the log file in USB drive here so we could look at it.

**Comment by chipochipo73** [comment]
Hi Xeon... I just noticed after I unplugged the thumb drive... The maps and weather is all gone.. Maybe will retain the weather later coz the widget looks empty at the bottom part...

I couldn't share any images... Not so sure why... Can't upload..

Thanks for the guide on the aa pop up message... It works..

But now the Google search tab doesn't connect to the phone... Hahaha..

Meaning when I click search on the goodle map on the screen previously.. My phone will activate the keyboard for me to type..

Now it's asking me type on the car screen.... Hahaha

**Comment by xeon1989** [comment]
You mean in Android Auto? There is a "Show keyboard on phone" button, i think on top left of keyboard.
Try tap that and see if keyboard now active on Phone.

![image](https://user-images.githubusercontent.com/17538895/234163907-fcec12cc-ce76-4654-8cdc-efacccac9b5b.png)

**Comment by chipochipo73** [comment]
Got it... Life. Saver... Maybe no glasses cannot see.. Hahaha... How come u can load pictures but I couldn't? Hmmm...

**Comment by rl-168** [comment]
Hi,
I also encounter the same issue with USB icon being gray out. This is the file in my fat32 formatted usb drive.
![Uploading IMG_0715.JPG…]()

**Comment by xeon1989** [comment]
@rl-168 i cant see the attached picture. please reattach it.

**Comment by rl-168** [comment]
Hi Chris,Whenever i attached it, it just came out as text so i m sending u hereThank you.Best regards,RickSent from my iPhoneOn 7 Jan 2024, at 13:04, Chris ***@***.***> wrote:﻿
@rl-168 i cant see the attached picture. please reattach it.

**Comment by rl-168** [comment]
I tried to attached the photo n file but both failed to display. I had replied to ur email instead

**Comment by xeon1989** [comment]
Hi, once attached in the reply, you need to wait for a moment for it to upload especially if the picture size is big.
I'm still not able to see the picture.
By replying the email, it sends to github noreply address, it will never reach my email.
Please reattach the picture again.

**Comment by rl-168** [comment]
Hi,
Hope u can see now.

![IMG_0715](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/124555658/0df694dd-ddc6-46fc-adcb-4576c324c474)

**Comment by xeon1989** [comment]
The hidden file in MacOS might brings unexpected outcome.
Could you try formatting the USB drive, then download the firmware and place it in USB drive on Windows machine please?

**Comment by rl-168** [comment]
Hi Chris,
I tried using a Windows PC n the results still the same where the USB icon is grey out. Below r the screenshots

![IMG_0717](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/124555658/7b05c31d-8792-4045-81fe-6cdf56e2cf5e)
![IMG_0716](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/124555658/61edc6e2-6d86-4d4a-96db-820032be7bf5)

**Comment by xeon1989** [comment]
Hi, I can see the set up in USB drive looks perfect.
You submitted Issue in past which means you sideloaded app before ,so I doubt the USB drive were formatted improperly.
That leads to last possibility which would be on the hardware side.
Can you try different USB drive please? Although it supposed to backward compatible with newer USB 3.0 drive but I found old USB 2.0 drive works every time.
Also check if the USB port are defective or not by placing mp3 files and play it over Media app.

**Comment by rl-168** [comment]
Hi Chris,
After switching to a USB2.0, i managed to run the downgrade n install the apps successfully. Thanks for ur support n u may close this case.
