### ISSUE TITLE
Not supported for X50 RC Premium

### ISSUE THREAD

**Issue by EwanZaidi** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#22]
Hi, 

Is this support for X50 RC Premium?

**Comment by ky960310** [comment]
X50_RC 2024 IHU using different hardware and Atlas OS version with X50_RA...Installation script for X50_RA cant be use with that X50_RC....For X50_RC its only compatible with PROTON GKUI/ATLAS HACKERS COMMUNITY community build installer file which is same build for X90 & S70 to carry out apps sideload...TQ..

https://chat.whatsapp.com/KkusevXd5ot5djZ8wPTV07
