### ISSUE TITLE
Is there a way to go back to Original Firmware for IHU?

### ISSUE THREAD

**Issue by David-TLCC** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#24]
I have been using Andriod Auto well about a year but recently about a month ago my Proton X50 IHU kept on loading (just like optimizing) things almost every time when a car turns on. As it takes about 5 mins, it really bothers my driving as I cannot control AC or Andriod Auto until the loading (optimizing) is finished.

I would like to restore IHU back to original and see if the same happens. 

Is there a way to restore or flash back the original IHU firmware?

Thanks in advance

**Comment by xeon1989** [comment]
Just reflash with the same firmware file and it will erase all custom apps
