### ISSUE TITLE
Mine USB button disabled. Cannot enter. Stuck at this stage

### ISSUE THREAD

**Issue by ikmalyunus** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#3]
![1686E496-BBDE-43B5-8F94-DC44DA89916D](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/135101856/90451ccd-4f6a-46f4-a730-247f1f0cb415)

**Comment by azhariyahaya** [comment]
Same goes to me. The USB icon not disable. Stuck here

**Comment by muncheno** [comment]
where is your firmware zip file?
Can share what is the filename?
It didn't detected your file, likely you didn't put in the correct folder.
