### ISSUE TITLE
Verification failed

### ISSUE THREAD

**Issue by arewan744** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#4]
Hi Xeon,

managed to get 100% on the verification steps but once completed the 100% it says verification failed. May I know this is because of what?. Corrupted file or the code dy5391 that I entered is wrong?. Any steps that I missed?

**Comment by xeon1989** [comment]
Sounds like file corrupted.
Tried redownload?

**Comment by arewan744** [comment]
Ok, I'll try to redownload. Is there a possibility that because I have the same version of firmware?. How to know whether I have v1 or v2?.

**Comment by xeon1989** [comment]
> Ok, I'll try to redownload. Is there a possibility that because I have the same version of firmware?. How to know whether I have v1 or v2?.

if you insert usb with script and it doesn't run, probably it's 617v2 if you sure you did everything right.

No, same firmware should still works, despite you have no reason to do so

**Comment by radio841** [comment]
i think either pendrive is not working properly. can change pendrive too.

**Comment by arewan744** [comment]
Issue resolved. Redownload & use different pendrive. Thanks
