### ISSUE TITLE
SW0SXRA0413H5170.00644 can?

### ISSUE THREAD

**Issue by ericjohn81** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#5]
Hi Chris, for current version as SW0SXRA0413H5170.00644 can still use this?
![WhatsApp Image 2023-06-10 at 7 36 27 AM](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/136133080/0e390423-593f-48d9-8b4b-11b9a9d244eb)
![WhatsApp Image 2023-06-10 at 7 36 33 AM](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/136133080/c7005912-842f-44b3-ae82-91ffc925dd6f)

**Comment by xeon1989** [comment]
I disabled OTA so I dont receive 644, thus I never try before.
However, we got testimonial by one of the bro that downgrade works.

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/34#issuecomment-1547222043

https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/issues/34#issuecomment-1547222043

**Comment by ericjohn81** [comment]
Thanks Chris. It works well on 644 as well
