### ISSUE TITLE
Atlas downgrade to gkui Exec/Std

### ISSUE THREAD

**Issue by radio841** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#6]
hi, it seems that atlas is not a good choice for me. can i have gkui firmware for exec? i want to downgrade to gkui again. T.T

**Comment by xeon1989** [comment]
Sorry but I do not have Exec GKUI firmware at the moment. :(

**Comment by Burgerkingpie** [comment]
Hi. Would it be possible to downgrade Atlas to GKUI version ?

**Comment by xeon1989** [comment]
@Burgerkingpie this is mentioned in https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/issues/8
Only available for Premium/Flagship and HW version 0090.
