### ISSUE TITLE
GKUI for hardware 0200

### ISSUE THREAD

**Issue by radio841** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#8]
Hi xeon, sorry if the request might be hard. but do you mind sharing firmware gkui for 0200 hw? tq in advance.

**Comment by ky960310** [comment]
> Hi xeon, sorry if the request might be hard. but do you mind sharing firmware gkui for 0200 hw? tq in advance. 

I would like to downgrade to Gkui as well but my hardware version is 0200, too bad the Gkui firmware I have is only for Premium/ Flagship hardware version 0090 😰

**Comment by xeon1989** [comment]
Hi @radio841 @ky960310 , I totally missed this issue. Thanks for bringing it up. 
I do not have GKUI firmware for hardware version 0200.
If anyone able to get one, feel free to share.

**Comment by ky960310** [comment]
> Hi @radio841 @ky960310 , I totally missed this issue. Thanks for bringing it up. 
> 
> I do not have GKUI firmware for hardware version 0200.
> 
> If anyone able to get one, feel free to share. 
> 
>  

One of my member is using gkui with hardware version 0200, do you know how to copy the firmware from his ihu to the pendrive? So that I can share it to everyone.. thanks
![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/131019179/f24fb79c-37da-4a62-a23a-3b5b7abf94a1)

**Comment by xeon1989** [comment]
@ky960310 Yes, I too have members also running GKUI on HW version 0200 with firmware version 41x.
The firmware already installed in IHU as running system in IHU.
I do not aware if it's possible to "extract" firmware from an Android devices.
Most likely would need a copy - as the firmware were digitally signed by ACO / Geely cert.
