### ISSUE TITLE
Model Exec. 

### ISSUE THREAD

**Issue by syamil-iman** [xeon1989/Proton-X50-IHU-Upgrade-Downgrade#9]
which one do i use as my model is executive but my firmware is 645 version?

**Comment by xeon1989** [comment]
Hi, could you please check the Hardware version in your IHU?

**Comment by syamil-iman** [comment]
HWSX11A0113LG090. This is the version.

**Comment by xeon1989** [comment]
The Standard/Executive ATLAS firmware posted in README.md should be compatible with your IHU.

| Model              | Current Firmware           | Download |
|--------------------|----------------------------|----------|
| Standard<br />Executive | GKUI: SW0SXRA1201L5064.00380 <br />ATLAS: SW0SXRA0616L5170.00582 <br />ATLAS: SW0SXRA1124L5170.00618(v2) | [Proton X50 Standard Executive.7z](https://drive.google.com/file/d/1hvU93XhB6K1q-e_x1XrCwucJmJDQLqzF/view?usp=share_link)   |

Please follow [the guide](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade) closely, if you decided to proceed with downgrade. 

Notes: noticed that you mentioned "Firmware FS" in title, what does it mean? FS firmware cannot be flashed in Executive IHU. (unless if you changed the screen. 😀 )

**Comment by syamil-iman** [comment]
I think I miss looked there because my firmware version “645” is same as fs/p firmware version. Btw, thank you.

**Comment by ky960310** [comment]
> I think I miss looked there because my firmware version “645” is same as fs/p firmware version. Btw, thank you. 

No bro.
Standard/ executive: 618 / 645
Premium/ flagship: 617/644

**Comment by syamil-iman** [comment]
![IMG_1572](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/132468814/de79bcf3-cdd5-4629-9403-1d818679705f)
Why can’t click? Already plugged in usb

**Comment by xeon1989** [comment]
@syamil-iman  Did you place 618 firmware in USB? Show us the content of USB drive please.

**Comment by syamil-iman** [comment]
![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/132468814/c9a0d805-11ed-40a6-ba13-e96cb6a15273)
yes 618 for sure.

**Comment by xeon1989** [comment]
You have to place the zip file in "Proton X50 Standard Executive" folder in the root directory of USB drive, alongside with "app" and "b832..." folders.

**Comment by ky960310** [comment]
> ![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/132468814/c9a0d805-11ed-40a6-ba13-e96cb6a15273)
> 
> yes 618 for sure.

Bro, not the whole firmware folder, just copy the firmware zip file and install script into your usb. 

![image](https://github.com/xeon1989/Proton-X50-IHU-Upgrade-Downgrade/assets/131019179/935839db-e3e3-4cc8-be00-2d16b1abc7b6)

U may refer to this tutorial video: 
https://vt.tiktok.com/ZSL27YhYt/
